language: java
jdk:
- oraclejdk8
install: true
script: ./gradlew build
notifications:
  slack:
    secure: DTU5atv8Er5OkicLPJTgLYDN3shir86onikDnZx4z1qAsTcHcthpTwOriEvYlFAgAwBH5PlRO5/q+I3Kz9XbLBmUkYZgE0DLHWDnkRRVxZsNVEJfDfypdylSP9QHuQD1+sHjUwYskMwLUvWYhEfk5fHE27bLre7KjRKdYmsI80GpOx93RovRVRzTiFX39bBydPEBMejLlzuVu4Pph+Zo2euRLrW3Nk0alYgLD11Zo+L2cQYWCERhK9kruYWCN8qUrM2FPhL9oToMTUhQ3/dUwvjlD10/dr1IDKPOam1BilU9rFGU2P/WPXaZLkCDDUMFq7NJiKX80kjoWB7os9ZVRkDUgi7Sy4soYQTDIGel2ZsWObWVQ+yL4udK/Adb+B9KYOGPylwexRuIBGdcxhf4cp5wGWgtFOTWm3bemv9FiMyIKaHkLH6UjcEBfRsLla02UtGBV2vN1SVxd4IchwxiJQfQe6jsBJnL8/qDh2u93SyhMd8mHaE6MAdfhzqwfSD9vFZc53nlZTKS56HB5ehawp9vISjPLbwvaR31aZQbDusKmAdjLUw2hQkfviThuA0U9AKMIrJazUnfXW1ohTUqfO7+DM0eMa0NByHm044e0CDANZW66IWf6ID9PY6zTjiszxLmvFfpjSsCBlE7WPQUT9AmYLa3XI2DVAICmJq39qw=
